Repository bitan2504/Weather-App, pull requests merged in 2025-02, with the labels that each got.

#16 suggestions implemented
  index.html
  script.js
Labels: enhancement, jwoc, jwoc2k25, medium

#19 Refactoring the home page design
  assets/bg-img.webp
  contact.html
  index.html
  script.js
  style.css
Labels: enhancement, jwoc, jwoc2k25, medium

#21 dark mode implemented with responsiveness
  about.css
  about.html
  contact.css
  contact.html
  index.html
  style.css
Labels: bug, enhancement, jwoc, jwoc2k25, hard

#28 faq section added
  about.html
  contact.html
  faq.css
  faq.html
  index.html
  style.css
Labels: jwoc, jwoc2k25, medium

#31 Feedback page added
  about.html
  contact.html
  faq.html
  feedback.css
  feedback.html
  feedback.js
  index.html
Labels: jwoc, jwoc2k25, medium

#30 Update Theme: Transition from Dark Mode to Light Mode UI
  about.css
  about.html
  contact.css
  contact.html
  faq.html
  index.html
  style.css
  theme.js
Labels: enhancement, jwoc, jwoc2k25, hard

#41 Introduce the logo click page redirect into the main page
  about.css
  about.html
  contact.css
  contact.html
  index.html
  style.css
Labels: bug, jwoc, jwoc2k25, easy

#43 [feature]Celsius-Fahrenheit toggling button
  index.html
  script.js
  style.css
Labels: enhancement, jwoc, jwoc2k25, medium

#46 privacy policy & terms and conditions page applied
  index.html
  privacy.html
  terms.html
Labels: jwoc, jwoc2k25, medium

#53 Fix the error popup while is failed to load the data
  index.html
  script.js
Labels: bug, jwoc, jwoc2k25, easy

#56 Made the navbar responsive also added hover effects to it
  about.html
  contact.html
  index.html
  style.css
Labels: enhancement, jwoc, jwoc2k25, medium
