Repository bitan2504/Weather-App, pull requests merged in 2025-03, with the labels that each got.

#63 Fix/fix toggle theme
  faq.html
Labels: bug, jwoc, jwoc2k25, medium

#65 faq navbar allignment fixed
  style.css
Labels: bug, jwoc, jwoc2k25, easy

#69 Fix:#55 Auto-Render Search Suggestions on Click
  script.js
Labels: bug, jwoc, jwoc2k25, easy

#73 Add the suggestion activity according to the current weather situation
  index.html
  script.js
  style.css
Labels: enhancement, jwoc, jwoc2k25, easy

#74 Added custom scrollbar
  style.css
Labels: enhancement, jwoc, jwoc2k25, easy

#75 Fixed color of Footer for dark mode
  style.css
Labels: bug, jwoc, jwoc2k25, easy
